{% set name = "qasync" %}
{% set version = "0.25.0" %}
{% set sha256 = "f4479f96f48d0899c4e37eb871fbd5084c2066bf21a4513f19ed2993b975a2f3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  requires:
    - pyqt
  imports:
    - qasync

about:
  home: https://github.com/CabbageDevelopment/qasync
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Implementation of the PEP 3156 Event-Loop with Qt.

  description: |
    qasync allows coroutines to be used in PyQt/PySide applications by
    providing an implementation of the PEP 3156 event-loop.
  dev_url: https://github.com/CabbageDevelopment/qasync

extra:
  recipe-maintainers:
    - ales-erjavec
