{% set name = "qasync" %}
{% set version = "0.18.1" %}
{% set sha256 = "08fb63d2c8ef00eb2b50fe490946f105b1c140db064e79c91d45dac86ae01c40" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  requires:
    - pyqt
  imports:
    - qasync

about:
  home: https://github.com/CabbageDevelopment/qasync
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Implementation of the PEP 3156 Event-Loop with Qt.

  description: |
    qasync allows coroutines to be used in PyQt/PySide applications by
    providing an implementation of the PEP 3156 event-loop.
  dev_url: https://github.com/CabbageDevelopment/qasync

extra:
  recipe-maintainers:
    - ales-erjavec
